version: '3.5'
services:
  api1:
    build:
      dockerfile: "./api.dockerfile"
    hostname: api1
    depends_on:
      - mongodb
      - rinhadb
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.5GB'

  api2:
    build:
      dockerfile: "./api.dockerfile"
    depends_on:
      - mongodb
      - rinhadb
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.5GB'

  rinhadb:
    build:
      dockerfile: "./rinhadb.dockerfile"
    ports:
      - "1313:1313"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '1GB'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.5GB'

  mongodb:
    # Banco de dados
    image: mongo:latest
    command: mongod --quiet --logpath /dev/null # desabilita o log do mongo (importante para desempenho)
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.5GB'

networks:
  default:
    driver: bridge
    name: rinha
